name: Build && Push

on:
  push:
    branches: [master]

jobs:
          
  build:
    name: Build and push Docker image with latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/scicatproject/backend:latest,ghcr.io/scicatproject/backend:${{ github.sha }}

  gitlab:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ESS pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: 1903
          ref: "master"
          host: "https://gitlab.esss.lu.se"
          debug: true

