name: Test && Build

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test and build image on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: |
          cp CI/ESS/docker-compose.gitlab.yaml docker-compose.yaml
          docker-compose down --remove-orphans
          docker-compose pull
          docker-compose up --build --exit-code-from scicat-backend
          docker-compose down

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: test_build
